name: route_event_task
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  injectable:
  get_it:
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
